### ISSUE TITLE
Wrong comparison expression in String Permutations

### ISSUE THREAD

**Issue by flavioheleno** [doganoo/PHPAlgorithms#9]
There is a wrong comparison in [Permutation.php#L54](https://github.com/doganoo/PHPAlgorithms/blob/master/src/Algorithm/Various/Permutation.php#L54), requiring a call to `permutation` for single character string permutations.

## Expected Behavior

Single character string permutations should return early in `Permutation.stringPermutations`.

## Current Behavior

Single character string permutations require a call to `permutation`, adding a minor overhead to `Permutation.stringPermutations`.

## Possible Solution

Replace `(1 === $string)` with `(1 === $strLen)`.

## Steps to Reproduce

1. Disable the private function `Permutation.permute`
2. Run the code below
```php
use doganoo\PHPAlgorithms\Algorithm\Various\Permutation;

$permutation  = new Permutation();
$permutations = $permutation->stringPermutations("a");
```

## Context (Environment)

I was reviewing the code out of curiosity and found the issue.

**Comment by doganoo** [comment]
thank you for the PR. I will merge this and it will be live with the next release 😊
